id: opecha:P006695
initial_creation_type: ocr
source_metadata:
  id: bdr:W2PD17448
  title: མཚོ་སྔོན་མི་རིགས་སློབ་གྲྭ་ཆེན་མོའི་བོད་རིག་པའི་སློབ་གླིང་གི་དུས་རབས ༢༡པའི་ཞིབ་འཇུག་སློབ་མའི་ཕུལ་བྱུང་མཐར་ཕྱིན་དཔྱད་རྩོམ་བདམས་བསྒྲིགས།
  volume: ''
  author: ''
